[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "streamframe"
version = "0.1.2"  
description = "Real-time feature computation engine for streaming data"
readme = "README.md"
requires-python = ">=3.8"

authors = [
  { name = "Sid" }
]

keywords = ["streaming", "real-time", "analytics", "feature-engineering"]

classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/sidkris/streamframe"
Repository = "https://github.com/sidkris/streamframe"
Issues = "https://github.com/sidkris/streamframe/issues"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "streamframe"